#this is the name used in eureka like this . Bacially the name of the microservice
spring.application.name=productservice
spring.profiles.active=dev
server.port=8080
spring.config.import=configserver:http://localhost:8888